site_name: Cakebox

site_description: Documentation for the Cakebox project.

dev_addr: 0.0.0.0:8000

docs_dir: docs/sources

include_search: true

theme: readthedocs

pages:

# Home:
- ['index.md', 'Home']

# Quickstart:
- ['quickstart.md', '', 'Quickstart']

# Features:
- ['features.md', '', 'Features']

# Cakebox.yaml:
- ['configuration/cakebox-yaml.md', '', 'Cakebox.yaml']

# SSH:
- ['configuration/ssh-connections.md', '', 'SSH Connections']


# Additional Information:
- ['additional/credentials.md', 'Additional Information', 'Usernames/Passwords']
- ['additional/known-limitations.md', 'Additional Information', 'Known Limitations']
