site_name: Cakebox

site_description: Documentation for the Cakebox project.

dev_addr: 0.0.0.0:8000

docs_dir: docs/sources

include_search: true

theme: readthedocs

pages:

# Home:
- ['index.md', 'Home']

# Features:
- ['features.md', '', 'Features']

# Quickstart:
- ['quickstart.md', '', 'Quickstart']

# SSH Connections:
- ['configuration/ssh-connections.md', '', 'SSH Connections']

# SSH Agent Forwarding:
- ['configuration/ssh-forwarding.md', '', 'SSH Agent Forwarding']

# Cakebox.yaml:
- ['configuration/cakebox-yml.md', '', 'Configuration']


# Additional Information:
- ['additional/credentials.md', 'Additional Information', 'Usernames/Passwords']
- ['additional/known-limitations.md', 'Additional Information', 'Known Limitations']
