site_name: Cakebox

site_description: Documentation for the Cakebox project.

dev_addr: 0.0.0.0:8000

docs_dir: docs/sources

include_search: true

theme: readthedocs

pages:

# Home:
- ['index.md', 'Home']

# Features:
- ['features.md', '', 'Features']

# Quickstart:
- ['quickstart.md', '', 'Quickstart']

# SSH Connections:
- ['configuration/ssh-connections.md', '', 'SSH Connections']

# SSH Agent Forwarding:
- ['configuration/ssh-forwarding.md', '', 'SSH Agent Forwarding']

# SSH Certificates:
- ['configuration/ssh-certificates.md', '', 'SSH Certificates']

# Cakebox.yaml:
- ['configuration/cakebox-yml.md', '', 'Configuration']

# Cakebox commands:
- ['usage/cakebox-commands.md', '', 'Cakebox Commands']

# Additional Information:
- ['additional/tutorial-first-site.md', 'Additional Information', 'Creating Your First Website']
- ['additional/credentials.md', 'Additional Information', 'Credentials']
- ['additional/known-limitations.md', 'Additional Information', 'Known Limitations']
